// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "Caret",
    // macOS 15 covers everything Caret uses (MenuBarExtra, Observation,
    // SMAppService, the Window scene) without pinning the app to the very
    // newest SDK. Raising this later is a one-line change.
    platforms: [.macOS(.v15)],
    targets: [
        // Pure logic: keyboard layouts, lexicons, the correction decision.
        // No AppKit windows, no event tap — so it is fully unit-testable.
        .target(
            name: "CaretCore",
            // Word lists harvested from the system lexicon by
            // Tools/HarvestWords.swift, trained into character models at launch.
            // Committed rather than generated at build time so that a build —
            // and every test that depends on a threshold — is reproducible on a
            // machine with different dictionaries installed.
            resources: [.copy("LanguageModels")],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        // The app itself: system integration (event tap, Accessibility,
        // replacement) and the entire user interface.
        .executableTarget(
            name: "Caret",
            dependencies: ["CaretCore"],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
        .testTarget(
            name: "CaretCoreTests",
            dependencies: ["CaretCore"],
            // A snapshot of the keyboard layouts the tests are written against,
            // so the suite does not depend on which input sources the machine
            // running it happens to have enabled. Regenerated by
            // Tools/DumpLayouts.swift.
            resources: [.copy("Layouts.json")],
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
